/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/HelloWorld copy 2.vue')['default']
    About: typeof import('./src/components/About.vue')['default']
    copy: typeof import('./src/components/HelloWorld copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LanguageCard: typeof import('./src/components/LanguageCard.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
